### ISSUE TITLE
Custom scrollbar with dark theme

### ISSUE THREAD

**Issue by mateusabelli** [mittal-parth/personal-portfolio#27]
### Styling the scrollbar

Hello, I would like to implement some styling to make the scrollbar have the same dark theme as the website.
Please let me know if it interests you, if it does, assign me and I will happily open a PR with the following code, the `--primary` and `--secondary` color variables, names, values are subject to change to respect the project styling.

```css
:root {
  --primary: #363636;
  --secondary: lightblue;
}

/* Firefox */
* {
  scrollbar-width: thin;
  scrollbar-color: var(--secondary) var(--primary);
}

/* Chrome, Edge, and Safari */
*::-webkit-scrollbar {
  width: 15px;
}

*::-webkit-scrollbar-track {
  background: var(--primary);
  border-radius: 0px;
}

*::-webkit-scrollbar-thumb {
  background-color: var(--secondary);
  border-radius: 14px;
  border: 3px solid var(--primary);
}
```

**Before**

![BEFORE](https://user-images.githubusercontent.com/43862225/193470711-c399588e-9834-4b3c-8ac0-90bb6967f64d.PNG)

**After**

![AFTER](https://user-images.githubusercontent.com/43862225/193470708-e58f7166-22a0-4247-b9fe-9abe58a9d202.PNG)
